'use strict';function u(e,a,b,d){e.A.pc(e.bb,a,b,d,void 0)}function C(e,a,b,d){e.A.da?u(e,a,b,d):e.A.kf()._OnMessageFromDOM({type:"event",component:e.bb,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function I(e,a,b){e.A.C(e.bb,a,b)}function K(e,a){for(const [b,d]of a)I(e,b,d)}function L(e){e.Sb||(e.A.Ve(e.fe),e.Sb=!0)}window.na=class{constructor(e,a){this.A=e;this.bb=a;this.Sb=!1;this.fe=()=>this.wa()}kd(){}wa(){}};function M(e){-1!==e.Sa&&(self.clearTimeout(e.Sa),e.Sa=-1)}
window.Me=class{constructor(e,a){this.Pc=e;this.xg=a;this.Sa=-1;this.Tb=-Infinity;this.ge=()=>{this.Sa=-1;this.Tb=Date.now();this.hb=!0;this.Pc();this.hb=!1};this.Od=this.hb=!1}c(){M(this);this.ge=this.Pc=null}};"use strict";function O(e,a){I(e,"get-element",b=>{const d=e.ca.get(b.elementId);return a(d,b)})}
window.Sg=class extends self.na{constructor(e,a){super(e,a);this.ca=new Map;this.Oc=!0;K(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ca.get(b);this.Oc&&d.parentElement.removeChild(d);this.ca.delete(b)}}],["set-visible",b=>{this.Oc&&(this.ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Oc){var d=this.ca.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ca.get(b.elementId);throw Error("required override");}],["focus",b=>this.Ic(b)],["set-css-style",b=>{this.ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ca.get(b.elementId).removeAttribute(b.name)}]]);O(this,b=>b)}Ic(e){var a=this.ca.get(e.elementId);e.focus?a.focus():a.blur()}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.Ig?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;c.textContent=m.Mg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let d=!1,g=!1;function n(){if(!d){try{new Worker("blob://",{get type(){g=!0}})}catch(m){}d=!0}return g}const q=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let w=new Audio;const B={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus")&&!q,"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;async function E(m){m=
await x(m);return(new TextDecoder("utf-8")).decode(m)}function x(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const y=[];let D=0;window.RealFile=window.File;const F=[],A=new Map,G=new Map;let J=0;const N=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");N.push(m)};const f=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.Z=class m{constructor(c){this.da=
c.Og;this.qa=null;this.F="";this.cc=c.Lg;this.wb={};this.La=this.vb=null;this.Qb=[];this.kb=this.K=this.Qa=null;this.Pa=-1;this.Cg=()=>this.If();this.Oa=[];this.s=c.he;this.ib="file"===location.protocol.substr(0,4);!this.da||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&n()||(this.da=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.da=!1;if("cordova"===this.s&&this.da)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],
10)||(this.da=!1)}else this.da=!1;this.Vb=this.ia=null;"html5"!==this.s&&"playable-ad"!==this.s||!this.ib||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.C("runtime","cordova-fetch-local-file",k=>this.sf(k));this.C("runtime","create-job-worker",()=>this.tf());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Bd(c)):this.Bd(c)}c(){this.vc();this.qa&&(this.qa=this.qa.onmessage=
null);this.vb&&(this.vb.terminate(),this.vb=null);this.La&&(this.La.c(),this.La=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}He(){return e&&"cordova"===this.s}oc(){const c=navigator.userAgent;return e&&f.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}async Bd(c){"macos-wkwebview"===this.s&&this.Mc({type:"ready"});if("playable-ad"===this.s){this.ia=self.c3_base64files;this.Vb={};await this.$e();for(let l=0,p=c.Ta.length;l<p;++l){var k=c.Ta[l].toLowerCase();
this.Vb.hasOwnProperty(k)?c.Ta[l]={Ig:!0,Mg:this.Vb[k]}:this.ia.hasOwnProperty(k)&&(c.Ta[l]=URL.createObjectURL(this.ia[k]))}}c.Dg?this.F=c.Dg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Qg&&(this.wb=c.Qg);k=new MessageChannel;this.qa=k.port1;this.qa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Ef(l));this.kb=new self.Ie(this);await P(this.kb);
"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.da?await this.mf(c,k.port2):await this.lf(c,k.port2)}yc(c){c=this.wb.hasOwnProperty(c)?this.wb[c]:c.endsWith("/workermain.js")&&this.wb.hasOwnProperty("workermain.js")?this.wb["workermain.js"]:"playable-ad"===this.s&&this.ia.hasOwnProperty(c.toLowerCase())?this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async ic(c,k,
l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.s&&this.ib)return c=await this.xb(l.Hg?c:this.cc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}za(){return Math.max(window.innerWidth,1)}ya(){return Math.max(window.innerHeight,1)}Ad(c){var k=
this.kb;return{baseUrl:this.F,windowInnerWidth:this.za(),windowInnerHeight:this.ya(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Wa(),projectData:c.Xg,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Vg||"",exportType:c.he,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Wg,jobScheduler:{inputPort:k.Vc,outputPort:k.cd,maxNumWorkers:k.zg},supportedAudioFormats:B,
opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.cc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.cc+"opus.wasm.wasm",isFileProtocol:this.ib,isiOSCordova:this.He(),isiOSWebView:this.oc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async mf(c,k){var l=this.yc(c.Pg);this.vb=await this.ic(l,this.F,{type:"module",name:"Runtime",Hg:!0});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);
window.c3canvas=this.K;let p=c.jd||[],v=c.Ta;p=await Promise.all(p.map(r=>this.Ha(r)));v=await Promise.all(v.map(r=>this.Ha(r)));if("cordova"===this.s)for(let r=0,t=c.fc.length;r<t;++r){const z=c.fc[r],H=z[0];if(H===c.gd||"scriptsInEvents.js"===H||H.endsWith("/scriptsInEvents.js"))z[1]=await this.Ha(H)}this.vb.postMessage(Object.assign(this.Ad(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:v,projectScripts:c.fc,mainProjectScript:c.gd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[k,l,...Q(this.kb)]);this.Qb=F.map(r=>new r(this));this.zd();self.c3_callFunction=(r,t)=>this.Qa.nf(r,t);"preview"===this.s&&(self.goToLastErrorScript=()=>this.pc("runtime","go-to-last-error-script"))}async lf(c,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Qb=F.map(r=>new r(this));this.zd();var l=c.Ta.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.jd)&&l.unshift(...c.jd);l=await Promise.all(l.map(r=>
this.Ha(r)));await Promise.all(l.map(r=>b(r)));l=self.C3_ProjectScriptsStatus;const p=c.gd,v=c.fc;for(let [r,t]of v)if(t||(t=r),r===p)try{t=await this.Ha(t),await b(t),"preview"!==this.s||l[r]||this.Jd(r,"main script did not run to completion")}catch(z){this.Jd(r,z)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))t=await this.Ha(t),await b(t);"preview"===this.s&&"object"!==typeof self.Rg.Tg?(this.Jb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Ad(c),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:N}),this.Dd(),this.La=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.La,c))}Jd(c,k){this.Jb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Dd(){this.Jb()}Jb(){const c=
window.Eg;c&&(c.parentElement.removeChild(c),window.Eg=null)}async tf(){const c=await R(this.kb);return{outputPort:c,transferables:[c]}}kf(){if(this.da)throw Error("not available in worker mode");return this.La}pc(c,k,l,p,v){this.qa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},v)}sd(c,k,l,p,v){const r=J++,t=new Promise((z,H)=>{G.set(r,{resolve:z,reject:H})});this.qa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},
v);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.yf(c);if("result"===k)this.Lf(c);else if("runtime-ready"===k)this.Mf();else if("alert-error"===k)this.Jb(),alert(c.message);else if("creating-runtime"===k)this.Dd();else throw Error(`unknown message '${k}'`);}yf(c){const k=c.component,l=c.handler,p=c.data,v=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==v&&this.Ib(v,!1,""+t);return}if(null===
v)return r;r&&r.then?r.then(t=>this.Ib(v,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Ib(v,!1,""+t)}):this.Ib(v,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Ib(c,k,l){let p;l&&l.transferables&&(p=l.transferables);this.qa.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}Lf(c){const k=c.responseId,l=c.isOk;c=c.result;const p=G.get(k);l?p.resolve(c):p.reject(c);G.delete(k)}C(c,
k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static ta(c){if(F.includes(c))throw Error("DOM handler already added");F.push(c)}zd(){for(const c of this.Qb)if("runtime"===c.bb){this.Qa=c;return}throw Error("cannot find runtime DOM handler");}Ef(c){this.pc("debugger","message",c)}Mf(){for(const c of this.Qb)c.kd()}static Wa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
h)}static Kb(c){h=!!c}Ve(c){this.Oa.push(c);this.Lc()}Yf(c){c=this.Oa.indexOf(c);if(-1===c)throw Error("invalid callback");this.Oa.splice(c,1);this.Oa.length||this.vc()}Lc(){-1===this.Pa&&this.Oa.length&&(this.Pa=requestAnimationFrame(this.Cg))}vc(){-1!==this.Pa&&(cancelAnimationFrame(this.Pa),this.Pa=-1)}If(){this.Pa=-1;for(const c of this.Oa)c();this.Lc()}xa(c){this.Qa.xa(c)}Ga(c){this.Qa.Ga(c)}Kc(){this.Qa.Kc()}Db(c){this.Qa.Db(c)}Ge(){return!!B["audio/webm; codecs=opus"]}async vg(c){c=await this.sd("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Fe(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}rd(c){return!this.Fe(c)}async Ha(c){return"cordova"===this.s&&(c.startsWith("file:")||this.ib&&this.rd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),c=await this.xb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async sf(c){const k=c.filename;switch(c.as){case "text":return await this.ye(k);case "buffer":return await this.xb(k);
default:throw Error("unsupported type");}}nd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,v=>{v.file(l,p)},p)})}async ye(c){c=await this.nd(c);return await E(c)}wc(){if(y.length&&!(8<=D)){D++;var c=y.shift();this.af(c.filename,c.Ng,c.Gg)}}xb(c){return new Promise((k,l)=>{y.push({filename:c,Ng:p=>{D--;this.wc();k(p)},Gg:p=>{D--;this.wc();l(p)}});this.wc()})}async af(c,k,l){try{const p=await this.nd(c),v=await x(p);
k(v)}catch(p){l(p)}}Mc(c){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async $e(){const c=[];for(const [k,l]of Object.entries(this.ia))c.push(this.Ze(k,l));await Promise.all(c)}async Ze(c,k){if("object"===typeof k)this.ia[c]=new Blob([k.str],{type:k.type}),this.Vb[c]=k.str;else{let l=await this.hf(k);l||(l=
this.cf(k));this.ia[c]=l}}async hf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}cf(c){c=this.Sf(c);return this.Ye(c.data,c.Jg)}Sf(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";
const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{Jg:c,data:l}}Ye(c,k){var l=c.length;let p=l>>2,v=new Uint8Array(l),r=new Uint32Array(v.buffer,0,p),t,z;for(z=t=0;t<p;++t)r[t]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=3;l--;)v[z]=c.charCodeAt(z),++z;return new Blob([v],{type:k})}}}"use strict";
{const e=self.Z;function a(f){return f.sourceCapabilities&&f.sourceCapabilities.firesTouchEvents||f.originalEvent&&f.originalEvent.sourceCapabilities&&f.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(f){return new Promise((h,m)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=f;document.head.appendChild(c)})}function w(f){return new Promise((h,m)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>m(k);c.src=f})}async function B(f){f=URL.createObjectURL(f);try{return await w(f)}finally{URL.revokeObjectURL(f)}}function E(f){return new Promise((h,m)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>m(k);c.readAsText(f)})}async function x(f,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(f);var c=await E(f);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(f)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);f=new Blob([c],{type:"image/svg+xml"});return await B(f)}function y(f){do{if(f.parentNode&&f.hasAttribute("contenteditable"))return!0;f=f.parentNode}while(f);return!1}const D=new Set(["input",
"textarea","datalist","select"]),F=new Set(["canvas","body","html"]);function A(f){F.has(f.target.tagName.toLowerCase())&&f.preventDefault()}function G(f){(f.metaKey||f.ctrlKey)&&f.preventDefault()}self.C3_GetSvgImageSize=async function(f){f=await B(f);if(0<f.width&&0<f.height)return[f.width,f.height];{f.style.position="absolute";f.style.left="0px";f.style.top="0px";f.style.visibility="hidden";document.body.appendChild(f);const h=f.getBoundingClientRect();document.body.removeChild(f);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(f,h,m,c,k){f=await x(f,h,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(f,0,0,h,m);return l};let J=!1;document.addEventListener("pause",()=>J=!0);document.addEventListener("resume",()=>J=!1);function N(){try{return window.parent&&window.parent.document.hasFocus()}catch(f){return!1}}e.ta(class extends self.na{constructor(f){super(f,"runtime");this.Td=!0;this.Ra=-1;this.ed="any";this.Kd=this.Ld=!1;this.Zc=
this.sb=this.Ba=null;f.C("canvas","update-size",c=>this.Pf(c));f.C("runtime","invoke-download",c=>this.Cf(c));f.C("runtime","raster-svg-image",c=>this.Jf(c));f.C("runtime","get-svg-image-size",c=>this.Af(c));f.C("runtime","set-target-orientation",c=>this.Nf(c));f.C("runtime","register-sw",()=>this.Kf());f.C("runtime","post-to-debugger",c=>this.Fd(c));f.C("runtime","go-to-script",c=>this.Fd(c));f.C("runtime","before-start-ticking",()=>this.rf());f.C("runtime","debug-highlight",c=>this.uf(c));f.C("runtime",
"enable-device-orientation",()=>this.Xe());f.C("runtime","enable-device-motion",()=>this.We());f.C("runtime","add-stylesheet",c=>this.qf(c));f.C("runtime","alert",c=>this.Cc(c));f.C("runtime","hide-cordova-splash",()=>this.Bf());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||y(k)||c.preventDefault()});const m=f.K;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",
A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.pb=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this.Qf());window.addEventListener("fullscreenchange",
()=>this.Ya());window.addEventListener("webkitfullscreenchange",()=>this.Ya());window.addEventListener("mozfullscreenchange",()=>this.Ya());window.addEventListener("fullscreenerror",c=>this.Ec(c));window.addEventListener("webkitfullscreenerror",c=>this.Ec(c));window.addEventListener("mozfullscreenerror",c=>this.Ec(c));f.oc()&&window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):y(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.Rf(c);this.Ma=new Set;this.Wb=new WeakSet;this.pa=!1}rf(){"cordova"===this.A.s?(document.addEventListener("pause",()=>this.Jc(!0)),document.addEventListener("resume",()=>this.Jc(!1))):document.addEventListener("visibilitychange",()=>this.Jc(document.hidden));return{isSuspended:!(!document.hidden&&!J)}}kd(){window.addEventListener("focus",()=>
this.$a("window-focus"));window.addEventListener("blur",()=>{this.$a("window-blur",{parentHasFocus:N()});this.pb=0});window.addEventListener("focusin",h=>{h=h.target;(D.has(h.tagName.toLowerCase())||y(h))&&this.$a("keyboard-blur")});window.addEventListener("keydown",h=>this.Ed("keydown",h));window.addEventListener("keyup",h=>this.Ed("keyup",h));window.addEventListener("dblclick",h=>this.Gc("dblclick",h,d));window.addEventListener("wheel",h=>this.Gf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.zc(h);this.Za("pointerdown",h)}),this.A.da&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.sb=new self.Me(()=>this.ff(),5),this.sb.Od=!0,window.addEventListener("pointerrawupdate",h=>this.Hf(h))):window.addEventListener("pointermove",h=>this.Za("pointermove",h)),window.addEventListener("pointerup",h=>this.Za("pointerup",h)),window.addEventListener("pointercancel",h=>this.Za("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.zc(h);this.Hc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Hc("pointermove",h)),window.addEventListener("mouseup",h=>this.Hc("pointerup",h)),window.addEventListener("touchstart",h=>{this.zc(h);this.Hb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Hb("pointermove",h)),window.addEventListener("touchend",h=>this.Hb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Hb("pointercancel",h)));const f=()=>this.Kc();window.addEventListener("pointerup",f,!0);window.addEventListener("touchend",
f,!0);window.addEventListener("click",f,!0);window.addEventListener("keydown",f,!0);window.addEventListener("gamepadconnected",f,!0)}$a(f,h){u(this,f,h||null,n)}za(){return this.A.za()}ya(){return this.A.ya()}Qf(){const f=this.za(),h=this.ya();this.$a("window-resize",{innerWidth:f,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.Wa()});this.A.oc()&&(-1!==this.Ra&&clearTimeout(this.Ra),this.Gd(f,h,0))}Zf(f,h,m){-1!==this.Ra&&clearTimeout(this.Ra);this.Ra=setTimeout(()=>this.Gd(f,
h,m),48)}Gd(f,h,m){const c=this.za(),k=this.ya();this.Ra=-1;c!=f||k!=h?this.$a("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.Wa()}):10>m&&this.Zf(c,k,m+1)}Nf(f){this.ed=f.targetOrientation}rg(){const f=this.ed;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(f):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(f):screen.mozLockOrientation?h=screen.mozLockOrientation(f):screen.msLockOrientation&&(h=screen.msLockOrientation(f));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Ya(){const f=e.Wa();f&&"any"!==this.ed&&this.rg();u(this,"fullscreenchange",{isFullscreen:f,innerWidth:this.za(),innerHeight:this.ya()})}Ec(f){console.warn("[Construct 3] Fullscreen request failed: ",f);u(this,"fullscreenerror",
{isFullscreen:e.Wa(),innerWidth:this.za(),innerHeight:this.ya()})}Jc(f){f?this.A.vc():this.A.Lc();u(this,"visibilitychange",{hidden:f})}Ed(f,h){"Backspace"===h.key&&A(h);const m=b.get(h.code)||h.code;C(this,f,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}Gf(f){u(this,"wheel",{clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,deltaX:f.deltaX,deltaY:f.deltaY,deltaZ:f.deltaZ,deltaMode:f.deltaMode,
timeStamp:f.timeStamp},d)}Gc(f,h,m){a(h)||C(this,f,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},m)}Hc(f,h){if(!a(h)){var m=this.pb;"pointerdown"===f&&0!==m?f="pointermove":"pointerup"===f&&0!==h.buttons&&(f="pointermove");C(this,f,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.pb=h.buttons;this.Gc(h.type,h,g)}}Za(f,h){if(this.sb&&"pointermove"!==f){var m=this.sb;m.hb||(M(m),m.Tb=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.pb);C(this,f,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);"mouse"===h.pointerType&&(m="mousemove","pointerdown"===f?m="mousedown":"pointerup"===f&&(m="mouseup"),this.Gc(m,h,g),this.pb=h.buttons)}Hf(f){this.Zc=f;f=this.sb;if(-1===f.Sa){var h=Date.now(),m=h-f.Tb,c=f.xg;m>=c&&f.Od?(f.Tb=h,f.hb=!0,f.Pc(),f.hb=!1):f.Sa=self.setTimeout(f.ge,Math.max(c-m,4))}}ff(){this.Za("pointermove",this.Zc);this.Zc=null}Hb(f,h){for(let m=0,c=h.changedTouches.length;m<c;++m){const k=h.changedTouches[m];C(this,f,{pointerId:k.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}zc(f){window!==window.top&&window.focus();this.Cd(f.target)&&document.activeElement&&!this.Cd(document.activeElement)&&document.activeElement.blur()}Cd(f){return!f||f===document||
f===window||f===document.body||"canvas"===f.tagName.toLowerCase()}Xe(){this.Ld||(this.Ld=!0,window.addEventListener("deviceorientation",f=>this.wf(f)),window.addEventListener("deviceorientationabsolute",f=>this.xf(f)))}We(){this.Kd||(this.Kd=!0,window.addEventListener("devicemotion",f=>this.vf(f)))}wf(f){u(this,"deviceorientation",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp,webkitCompassHeading:f.webkitCompassHeading,webkitCompassAccuracy:f.webkitCompassAccuracy},
d)}xf(f){u(this,"deviceorientationabsolute",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp},d)}vf(f){let h=null;var m=f.acceleration;m&&(h={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=f.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=f.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});u(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:c,interval:f.interval,timeStamp:f.timeStamp},
d)}Pf(f){const h=this.A.K;h.style.width=f.styleWidth+"px";h.style.height=f.styleHeight+"px";h.style.marginLeft=f.marginLeft+"px";h.style.marginTop=f.marginTop+"px";this.Td&&(h.style.display="",this.Td=!1)}Cf(f){const h=f.url;f=f.filename;const m=document.createElement("a"),c=document.body;m.textContent=f;m.href=h;m.download=f;c.appendChild(m);m.click();c.removeChild(m)}async Jf(f){var h=f.imageBitmapOpts;f=await self.C3_RasterSvgImageBlob(f.blob,f.imageWidth,f.imageHeight,f.surfaceWidth,f.surfaceHeight);
h=h?await createImageBitmap(f,h):await createImageBitmap(f);return{imageBitmap:h,transferables:[h]}}async Af(f){return await self.C3_GetSvgImageSize(f.blob)}async qf(f){await q(f.url)}Kc(){var f=[...this.Ma];this.Ma.clear();if(!this.pa)for(const h of f)(f=h.play())&&f.catch(()=>{this.Wb.has(h)||this.Ma.add(h)})}xa(f){if("function"!==typeof f.play)throw Error("missing play function");this.Wb.delete(f);let h;try{h=f.play()}catch(m){this.Ma.add(f);return}h&&h.catch(()=>{this.Wb.has(f)||this.Ma.add(f)})}Ga(f){this.Ma.delete(f);
this.Wb.add(f)}Db(f){this.pa=!!f}Bf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}uf(f){if(f.show){this.Ba||(this.Ba=document.createElement("div"),this.Ba.id="inspectOutline",document.body.appendChild(this.Ba));var h=this.Ba;h.style.display="";h.style.left=f.left-1+"px";h.style.top=f.top-1+"px";h.style.width=f.width+2+"px";h.style.height=f.height+2+"px";h.textContent=f.name}else this.Ba&&(this.Ba.style.display="none")}Kf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Fd(f){window.c3_postToMessagePort&&
(f.from="runtime",window.c3_postToMessagePort(f))}nf(f,h){return this.A.sd(this.bb,"js-invoke-function",{name:f,params:h},void 0,void 0)}Cc(f){alert(f.message)}Rf(f){"entered-fullscreen"===f?(e.Kb(!0),this.Ya()):"exited-fullscreen"===f?(e.Kb(!1),this.Ya()):console.warn("Unknown wrapper message: ",f)}})}"use strict";
async function P(e){if(e.wg)throw Error("already initialised");e.wg=!0;var a=e.bc.yc("dispatchworker.js");e.Rc=await e.bc.ic(a,e.F,{name:"DispatchWorker"});a=new MessageChannel;e.Vc=a.port1;e.Rc.postMessage({type:"_init","in-port":a.port2},[a.port2]);e.cd=await R(e)}function Q(e){return[e.Vc,e.cd]}
async function R(e){const a=e.Vd.length;var b=e.bc.yc("jobworker.js");b=await e.bc.ic(b,e.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;e.Rc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);e.Vd.push(b);return g.port1}
self.Ie=class{constructor(e){this.bc=e;this.F=e.F;this.F="preview"===e.s?this.F+"workers/":this.F+e.cc;this.zg=Math.min(navigator.hardwareConcurrency||2,16);this.Rc=null;this.Vd=[];this.cd=this.Vc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Z({Og:!1,Pg:"workermain.js",Ta:["scripts/c3runtime.js"],fc:[],gd:"",Lg:"scripts/",jd:[],he:"html5"}));"use strict";
async function S(e){var a=T(e.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:e.duration,startDelay:0,weakMagnitude:e.weakMag,strongMagnitude:e.strongMag})}catch(b){console.warn("[Gamepad] Failed to vibrate gamepad: ",b)}}function U(){return Array.from(navigator.getGamepads()).filter(e=>e&&e.connected)}function T(e){for(const a of U())if(a.index===e)return a;return null}
self.Z.ta(class extends self.na{constructor(e){super(e,"gamepad");this.Ud=!!navigator.getGamepads;this.Xc=!1;I(this,"is-supported",()=>this.Ud);I(this,"ready",()=>{this.Xc=!0;for(const a of U())u(this,"gamepad-connected",{index:a.index,id:a.id});this.Ud&&L(this)});I(this,"vibrate",a=>S(a));I(this,"reset-vibrate",a=>{(a=T(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.Xc&&(a=a.gamepad,u(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.Xc&&u(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of U()){const b=a.vibrationActuator;b&&b.reset&&b.reset()}})}wa(){var e=U();e.length&&(e=e.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(b=>({pressed:b.pressed,value:b.value})),axes:a.axes})),u(this,"input-update",e))}});"use strict";
function V(e){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>u(e,"sw-message",a.data))}
function aa(e){e=e.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(e):screen.webkitLockOrientation?a=screen.webkitLockOrientation(e):screen.mozLockOrientation?a=screen.mozLockOrientation(e):screen.msLockOrientation&&(a=screen.msLockOrientation(e));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.Z.ta(class extends self.na{constructor(e){super(e,"browser");this.s="";K(this,[["get-initial-state",a=>this.Fc(a)],["ready-for-sw-messages",()=>V(this)],["alert",a=>this.Cc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ic(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>aa(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===
b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.Ug||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.Z.Kb(!0),
this.A.Mc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",
()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.Z.Kb(!1),this.A.Mc({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{u(this,"online-state",{isOnline:!0})});window.addEventListener("offline",
()=>{u(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{u(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{u(this,"backbutton")})}Fc(e){this.s=e.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}Cc(e){alert(e.message)}Ic(e){e=e.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;e?a.focus():a.blur()}else e?window.focus():window.blur()}});"use strict";self.Z.ta(class extends self.na{constructor(e){super(e,"mouse");I(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
async function ba(e){if(!e.Da)try{e.Da=await navigator.wakeLock.request("screen"),e.Da.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");e.Da=null;u(e,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),u(e,"wake-lock-acquired")}catch(a){console.warn("[Construct 3] Failed to acquire screen wake lock: ",a),u(e,"wake-lock-error")}}
function W(){var e=document.body;const a=e.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");e=getComputedStyle(e);e=[e.getPropertyValue("--temp-sai-top"),e.getPropertyValue("--temp-sai-right"),e.getPropertyValue("--temp-sai-bottom"),e.getPropertyValue("--temp-sai-left")].map(b=>{b=parseInt(b,10);
return isFinite(b)?b:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return e}
self.Z.ta(class extends self.na{constructor(e){super(e,"platform-info");K(this,[["get-initial-state",()=>this.Fc()],["request-wake-lock",()=>ba(this)],["release-wake-lock",()=>{this.Da&&(this.Da.release(),this.Da=null)}]]);window.addEventListener("resize",()=>{u(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:W()})});this.Da=null}Fc(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:W(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";async function ca(e,a){a=a.type;let b=!0;0===a?b=await da():1===a&&(b=await fa());u(e,"permission-result",{type:a,result:b})}async function da(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request orientation permission: ",e),!1}}
async function fa(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request motion permission: ",e),!1}}self.Z.ta(class extends self.na{constructor(e){super(e,"touch");I(this,"request-permission",a=>ca(this,a))}});"use strict";
{const e=180/Math.PI;self.ea=class extends self.na{constructor(a){super(a,"audio");this.Pb=this.f=null;this.Rb=this.Uc=!1;this.sa=()=>this.sg();this.aa=[];this.D=[];this.ha=null;this.Wd="";this.Xd=-1;this.rb=new Map;this.$c=1;this.pa=!1;this.fd=0;this.dc=1;this.Sc=0;this.Zd="HRTF";this.Pd="inverse";this.$d=600;this.Yd=1E4;this.be=1;this.Rd=this.dd=!1;this.ee=this.A.Ge();this.ba=new Map;this.Ja=new Set;this.Wc=!1;this.ad="";this.Ca=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Ff(b,d);this.Ob=null;
self.C3Audio_GetOutputStream=()=>this.zf();self.C3Audio_DOMInterface=this;K(this,[["create-audio-context",b=>this.bf(b)],["play",b=>this.Tf(b)],["stop",b=>this.pg(b)],["stop-all",()=>this.qg()],["set-paused",b=>this.ig(b)],["set-volume",b=>this.ng(b)],["fade-volume",b=>this.gf(b)],["set-master-volume",b=>this.gg(b)],["set-muted",b=>this.hg(b)],["set-silent",b=>this.kg(b)],["set-looping",b=>this.fg(b)],["set-playback-rate",b=>this.jg(b)],["seek",b=>this.$f(b)],["preload",b=>this.Uf(b)],["unload",b=>
this.tg(b)],["unload-all",()=>this.ug()],["set-suspended",b=>this.lg(b)],["add-effect",b=>this.xd(b)],["set-effect-param",b=>this.cg(b)],["remove-effects",b=>this.Wf(b)],["tick",b=>this.Of(b)],["load-state",b=>this.Df(b)]])}async bf(a){a.isiOSCordova&&(this.dd=!0);this.fd=a.timeScaleMode;this.Zd=["equalpower","HRTF","soundfield"][a.panningModel];this.Pd=["linear","inverse","exponential"][a.distanceModel];this.$d=a.refDistance;this.Yd=a.maxDistance;this.be=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ee||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.yd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.yd()};this.Pb=this.f.createGain();this.Pb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.jc();try{await Promise.all(a.preloadList.map(d=>this.Fb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}yd(){this.Rb||(this.Uc=!1,window.addEventListener("pointerup",this.sa,!0),window.addEventListener("touchend",this.sa,!0),window.addEventListener("click",this.sa,!0),window.addEventListener("keydown",this.sa,!0),this.Rb=!0)}df(){this.Rb&&(this.Uc=!0,window.removeEventListener("pointerup",this.sa,!0),window.removeEventListener("touchend",
this.sa,!0),window.removeEventListener("click",this.sa,!0),window.removeEventListener("keydown",this.sa,!0),this.Rb=!1)}sg(){if(!this.Uc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.df()}}W(){return this.f}jc(){return this.f.currentTime}ua(){return this.Pb}pd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.ua()}ie(a,b){a=a.toLowerCase();let d=this.ba.get(a);
d||(d=[],this.ba.set(a,d));b.eg(d.length);b.mg(a);d.push(b);this.Id(a)}Id(a){let b=this.ua();const d=this.ba.get(a);if(d&&d.length){b=d[0].P();for(let g=0,n=d.length;g<n;++g){const q=d[g];g+1===n?q.S(this.ua()):q.S(d[g+1].P())}}for(const g of this.ma(a))g.Ne(b);this.Ca&&this.ad===a&&(this.Ca.disconnect(),this.Ca.connect(b))}zb(){return this.$c}Ab(){return this.pa}dg(){this.Rd=!0}Ae(a,b){return b?this.A.vg(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):
new Promise((d,g)=>{this.f.decodeAudioData(a,d,g)})}xa(a){this.A.xa(a)}Ga(a){this.A.Ga(a)}td(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const n=this.D[d];this.D[b]=n;n.L===a?n.c():++b}this.D.length=b}Oe(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const g=this.aa[b];this.aa[a]=g;g.va()?g.c():++a}this.aa.length=a}*ma(a){if(a)for(const b of this.D)self.ea.Be(b.Y,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Fb(a,b,d,g,n){for(const q of this.aa)if(q.Va()===b)return await X(q),
q;if(n)return null;g&&(this.dd||this.Rd)&&this.Oe();n="audio/webm; codecs=opus"===d&&!this.ee;g&&n&&this.dg();a=!g||this.dd||n?new self.we(this,a,b,d,g,n):new self.ue(this,a,b,d,g);this.aa.push(a);await X(a);return a}async xc(a,b,d,g,n){for(const q of this.D)if(q.Va()===b&&(q.hc()||n))return q.Qe(g),q;a=await this.Fb(a,b,d,n);g="html5"===a.Nc?new self.ve(a.i,a,g):new self.xe(a.i,a,g);this.D.push(g);return g}Ue(a){let b=this.rb.get(a);if(!b){let d=null;b={hd:0,Kg:new Promise(g=>d=g),resolve:d};this.rb.set(a,
b)}b.hd++}Xf(a){const b=this.rb.get(a);if(!b)throw Error("expected pending tag");b.hd--;0===b.hd&&(b.resolve(),this.rb.delete(a))}uc(a){a||(a=this.Wd);return(a=this.rb.get(a))?a.Kg:Promise.resolve()}Gb(){if(0<this.Ja.size)L(this);else for(const a of this.D)if(a.qd()){L(this);break}}wa(){for(var a of this.Ja)a.wa();a=this.jc();for(var b of this.D)b.wa(a);b=this.D.filter(d=>d.qd()).map(d=>d.Ua());u(this,"state",{tickCount:this.Xd,audioInstances:b,analysers:[...this.Ja].map(d=>d.De())});0===b.length&&
0===this.Ja.size&&this.Sb&&(this.A.Yf(this.fe),this.Sb=!1)}qc(a,b,d){u(this,"trigger",{type:a,tag:b,aiid:d})}async Tf(a){const b=a.originalUrl,d=a.url,g=a.type,n=a.isMusic,q=a.tag,w=a.isLooping,B=a.vol,E=a.pos,x=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.f.currentTime);this.Wd=q;this.Ue(q);try{this.ha=await this.xc(b,d,g,q,n),x?(this.ha.Cb(!0),this.ha.Pe(x.x,x.y,x.angle,
x.innerAngle,x.outerAngle,x.outerGain),x.hasOwnProperty("uid")&&this.ha.Re(x.uid)):this.ha.Cb(!1),this.ha.Play(w,B,E,y)}catch(D){console.error("[Construct 3] Audio: error starting playback: ",D);return}finally{this.Xf(q)}L(this)}pg(a){a=a.tag;for(const b of this.ma(a))b.oa()}qg(){for(const a of this.D)a.oa()}ig(a){const b=a.tag;a=a.paused;for(const d of this.ma(b))a?d.Xa():d.Bb();this.Gb()}ng(a){const b=a.tag;a=a.vol;for(const d of this.ma(b))d.Eb(a)}async gf(a){const b=a.tag,d=a.vol,g=a.duration;
a=a.stopOnEnd;await this.uc(b);for(const n of this.ma(b))n.Ce(d,g,a);this.Gb()}gg(a){this.$c=a.vol;for(const b of this.D)b.Mb()}hg(a){const b=a.tag;a=a.isMuted;for(const d of this.ma(b))d.ud(a)}kg(a){this.pa=a.isSilent;this.A.Db(this.pa);for(const b of this.D)b.Lb()}fg(a){const b=a.tag;a=a.isLooping;for(const d of this.ma(b))d.sc(a)}async jg(a){const b=a.tag;a=a.rate;await this.uc(b);for(const d of this.ma(b))d.wd(a)}async $f(a){const b=a.tag;a=a.pos;await this.uc(b);for(const d of this.ma(b))d.rc(a)}async Uf(a){const b=
a.originalUrl,d=a.url,g=a.type;a=a.isMusic;try{await this.xc(b,d,g,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async tg(a){if(a=await this.Fb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}ug(){for(const a of this.aa)a.c();this.aa.length=0}lg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.tc(a);a&&this.f.suspend&&this.f.suspend()}Of(a){this.dc=a.timeScale;this.Sc=a.gameTime;this.Xd=a.tickCount;if(0!==
this.fd)for(var b of this.D)b.Ia();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.ga===a&&g.vd(d.x,d.y,d.angle)}}async xd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.oe(this,...g);else if("delay"===b)g=new self.me(this,...g);else if("convolution"===b){b=null;try{b=await this.Fb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}g=new self.le(this,b.$,...g);g.ag(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.pe(this,...g);else if("phaser"===b)g=new self.re(this,...g);else if("gain"===b)g=new self.qe(this,...g);else if("tremolo"===b)g=new self.te(this,...g);else if("ringmod"===b)g=new self.se(this,...g);else if("distortion"===b)g=new self.ne(this,...g);else if("compressor"===b)g=new self.ke(this,...g);else if("analyser"===b)g=new self.je(this,...g);else throw Error("invalid effect type");this.ie(d,
g);this.Hd()}cg(a){const b=a.index,d=a.param,g=a.value,n=a.ramp,q=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,n,q),this.Hd())}Wf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.c();this.ba.delete(a);this.Id(a)}}Te(a){this.Ja.add(a);this.Gb()}Vf(a){this.Ja.delete(a)}Hd(){this.Wc||(this.Wc=!0,Promise.resolve().then(()=>this.ef()))}ef(){const a={};for(const [b,d]of this.ba)a[b]=d.map(g=>g.Ua());u(this,"fxstate",{fxstate:a});this.Wc=!1}async Df(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.va()&&1===b||(d.va()||2!==b)&&d.oa();for(const g of this.ba.values())for(const n of g)n.c();this.ba.clear();this.dc=a.timeScale;this.Sc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.pa=a.isSilent;this.A.Db(this.pa);this.$c=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(n=>this.xd(n))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.pf(g,b)));this.Gb()}async pf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,g=a.bufferUrl,n=a.bufferType,q=a.isMusic,w=a.tag,B=a.isLooping,E=a.volume,x=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.xc(d,g,n,w,q)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.Le(a.pan);b.Play(B,E,x,0);a.isPlaying||b.Xa();b.Bc(a)}}}Ff(a,b){this.Ca&&this.Ca.disconnect();this.ad=b.toLowerCase();this.Ca=this.f.createMediaStreamSource(a);this.Ca.connect(this.pd(this.ad))}zf(){this.Ob||(this.Ob=this.f.createMediaStreamDestination(),
this.Pb.connect(this.Ob));return this.Ob.stream}static Be(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Se(a){return a*e}static ze(a){return Math.pow(10,a/20)}static od(a){return Math.max(Math.min(self.ea.ze(a),1),0)}static Ke(a){return Math.log(a)/Math.log(10)*20}static Je(a){return self.ea.Ke(Math.max(Math.min(a,1),0))}static Fg(a,b){return 1-Math.exp(-b*a)}};self.Z.ta(self.ea)}"use strict";function X(e){e.Ub||(e.Ub=e.Ac());return e.Ub}
self.ld=class{constructor(e,a,b,d,g){this.i=e;this.Bg=a;this.Ea=b;this.R=d;this.yg=g;this.Nc="";this.Ub=null}c(){this.Ub=this.i=null}Ac(){}W(){return this.i.W()}lc(){return this.Bg}Va(){return this.Ea}kc(){return this.R}va(){return this.yg}fa(){}};"use strict";
self.ue=class extends self.ld{constructor(e,a,b,d,g){super(e,a,b,d,g);this.Nc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.lb=this.mb=null;this.J.addEventListener("canplaythrough",()=>!0);this.qb=this.W().createGain();this.ob=null;this.J.addEventListener("canplay",()=>{this.mb&&(this.mb(),this.lb=this.mb=null);!this.ob&&this.J&&(this.ob=this.W().createMediaElementSource(this.J),this.ob.connect(this.qb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.Ea}' error: `,n);this.lb&&(this.lb(n),this.lb=this.mb=null)})}c(){this.i.td(this);this.qb.disconnect();this.qb=null;this.ob.disconnect();this.ob=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Ac(){return new Promise((e,a)=>{this.mb=e;this.lb=a;this.J.src=this.Ea})}O(){return this.J}fa(){return this.J.duration}};"use strict";
async function ha(e){if(e.Aa)return e.Aa;var a=e.i.A;if("cordova"===a.s&&a.rd(e.Ea)&&a.ib)e.Aa=await a.xb(e.Ea);else{a=await fetch(e.Ea);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);e.Aa=await a.arrayBuffer()}}async function ia(e){if(e.$)return e.$;e.$=await e.i.Ae(e.Aa,e.Ag);e.Aa=null}
self.we=class extends self.ld{constructor(e,a,b,d,g,n){super(e,a,b,d,g);this.Nc="webaudio";this.$=this.Aa=null;this.Ag=!!n}c(){this.i.td(this);this.$=this.Aa=null;super.c()}async Ac(){try{await ha(this),await ia(this)}catch(e){console.error(`[Construct 3] Failed to load audio '${this.Ea}': `,e)}}fa(){return this.$?this.$.duration:0}};"use strict";
{let e=0;self.md=class{constructor(a,b,d){this.i=a;this.L=b;this.Y=d;this.Nb=e++;this.M=this.W().createGain();this.M.connect(this.ua());this.B=null;this.jb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.H=!0;this.V=this.la=this.G=!1;this.ub=1;this.Ka=!1;this.ra=1;a=this.i.fd;this.Yc=1===a&&!this.va()||2===a;this.fb=this.ga=-1;this.de=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ua(){return this.i.pd(this.Y)}zb(){return this.i.zb()}yb(){return this.Yc?
this.i.Sc:performance.now()/1E3}lc(){return this.L.lc()}Va(){return this.L.Va()}kc(){return this.L.kc()}va(){return this.L.va()}Qe(a){this.Y=a}T(){}hc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}qd(){return!this.H&&!this.T()}Fa(){}fa(){return this.L.fa()}Play(){}oa(){}Xa(){}Bb(){}Eb(a){this.ub=a;this.M.gain.cancelScheduledValues(0);this.fb=-1;this.M.gain.value=this.mc()}Ce(a,b,d){if(!this.Ka){a*=this.zb();var g=this.M.gain;g.cancelScheduledValues(0);var n=this.i.jc();b=n+b;g.setValueAtTime(g.value,
n);g.linearRampToValueAtTime(a,b);this.ub=a;this.fb=b;this.de=d}}Mb(){this.Eb(this.ub)}wa(a){-1!==this.fb&&a>=this.fb&&(this.fb=-1,this.de&&this.oa(),this.i.qc("fade-ended",this.Y,this.Nb))}mc(){const a=this.ub*this.zb();return isFinite(a)?a:0}ud(a){a=!!a;this.Ka!==a&&(this.Ka=a,this.Lb())}Ab(){return this.i.Ab()}Lb(){}sc(){}wd(a){this.ra!==a&&(this.ra=a,this.Ia())}Ia(){}rc(){}tc(){}Cb(a){a=!!a;this.jb!==a&&((this.jb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.Zd,this.B.distanceModel=
this.i.Pd,this.B.refDistance=this.i.$d,this.B.maxDistance=this.i.Yd,this.B.rolloffFactor=this.i.be),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ua())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ua())))}Pe(a,b,d,g,n,q){this.jb&&(this.vd(a,b,d),a=self.ea.Se,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}vd(a,b,d){this.jb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(d),this.ja[1]=Math.sin(d),this.ja[2]=0,this.B.setPosition(...this.ka),
this.B.setOrientation(...this.ja))}Re(a){this.ga=a}nc(){}Ne(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ua(){return{aiid:this.Nb,tag:this.Y,duration:this.fa(),volume:this.ub,isPlaying:this.IsPlaying(),playbackTime:this.Fa(),playbackRate:this.ra,uid:this.ga,bufferOriginalUrl:this.lc(),bufferUrl:"",bufferType:this.kc(),isMusic:this.va(),isLooping:this.V,isMuted:this.Ka,resumePosition:this.nc(),pan:this.Ee()}}Bc(a){this.wd(a.playbackRate);this.ud(a.isMuted)}Ee(){if(!this.B)return null;const a=
this.B;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Le(a){if(a){this.Cb(!0);a=this.B;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Cb(!1)}}}"use strict";
self.ve=class extends self.md{constructor(e,a,b){super(e,a,b);this.L.qb.connect(this.M);this.L.onended=()=>this.Dc()}c(){this.oa();this.L.qb.disconnect();super.c()}O(){return this.L.O()}Dc(){this.H=!0;this.ga=-1;this.i.qc("ended",this.Y,this.Nb)}T(){return this.O().ended}hc(){return this.H?!0:this.T()}Fa(){let e=this.O().currentTime;this.V||(e=Math.min(e,this.fa()));return e}Play(e,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==e&&(d.loop=e);this.Eb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Va()}' to position '${b}': `,g)}this.i.xa(d);this.G=this.H=!1;this.V=e;this.ra=1}oa(){const e=this.O();e.paused||e.pause();this.i.Ga(e);this.H=!0;this.G=!1;this.ga=-1}Xa(){if(!(this.G||this.H||this.T())){var e=this.O();e.paused||e.pause();this.i.Ga(e);this.G=!0}}Bb(){!this.G||this.H||this.T()||(this.i.xa(this.O()),this.G=!1)}Lb(){this.O().muted=this.Ka||this.Ab()}sc(e){e=!!e;this.V!==e&&
(this.V=e,this.O().loop=e)}Ia(){let e=this.ra;this.Yc&&(e*=this.i.dc);try{this.O().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}rc(e){if(!this.H&&!this.T())try{this.O().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,a)}}nc(){return this.Fa()}tc(e){e?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.xa(this.O()),this.la=!1)}};"use strict";
function Y(e){e.j&&e.j.disconnect();e.j=null;e.ab=null}
self.xe=class extends self.md{constructor(e,a,b){super(e,a,b);this.j=null;this.Xb=d=>this.Dc(d);this.Tc=!0;this.ab=null;this.N=this.Yb=this.Zb=0;this.bd=1}c(){this.oa();Y(this);this.Xb=null;super.c()}Dc(e){this.G||this.la||e.target!==this.ab||(this.H=this.Tc=!0,this.ga=-1,Y(this),this.i.qc("ended",this.Y,this.Nb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Tc}hc(){return!this.j||this.H?!0:this.T()}Fa(){let e;e=this.G?this.N:this.Yb+(this.yb()-this.Zb)*this.ra;this.V||(e=Math.min(e,this.fa()));
return e}Play(e,a,b,d){this.bd=1;this.Eb(a);Y(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.ab=this.j;this.j.onended=this.Xb;this.j.loop=e;this.j.start(d,b);this.G=this.H=this.Tc=!1;this.V=e;this.ra=1;this.Zb=this.yb();this.Yb=b}oa(){if(this.j)try{this.j.stop(0)}catch(e){}this.H=!0;this.G=!1;this.ga=-1}Xa(){this.G||this.H||this.T()||(this.N=this.Fa(),this.V&&(this.N%=this.fa()),this.G=!0,this.j.stop(0))}Bb(){!this.G||this.H||this.T()||(Y(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Mb(),this.Ia(),this.j.start(0,this.N),this.Zb=this.yb(),this.Yb=this.N,this.G=!1)}mc(){return super.mc()*this.bd}Lb(){this.bd=this.Ka||this.Ab()?0:1;this.Mb()}sc(e){e=!!e;this.V!==e&&(this.V=e,this.j&&(this.j.loop=e))}Ia(){let e=this.ra;this.Yc&&(e*=this.i.dc);this.j&&(this.j.playbackRate.value=e)}rc(e){this.H||this.T()||(this.G?this.N=e:(this.Xa(),this.N=e,this.Bb()))}nc(){return this.N}tc(e){e?
this.IsPlaying()?(this.la=!0,this.N=this.Fa(),this.V&&(this.N%=this.fa()),this.j.stop(0)):this.la=!1:this.la&&(Y(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Mb(),this.Ia(),this.j.start(0,this.N),this.Zb=this.yb(),this.Yb=this.N,this.la=!1)}Bc(e){super.Bc(e);this.N=e.resumePosition}};"use strict";
{class e{constructor(a){this.i=a;this.f=a.W();this.Sd=-1;this.R=this.Y="";this.g=null}c(){this.f=null}eg(a){this.Sd=a}mg(a){this.Y=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var n=this.f.currentTime;g+=n;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,g)}}}Ua(){return{type:this.R,tag:this.Y,params:this.g}}}
self.oe=class extends e{constructor(a,b,d,g,n,q,w){super(a);this.R="filter";this.g=[b,d,g,n,q,w];this.l=this.o();this.b=this.o();this.b.gain.value=w;this.a=this.o();this.a.gain.value=1-w;this.v=this.f.createBiquadFilter();this.v.type=b;this.v.frequency.value=d;this.v.detune.value=g;this.v.Q.value=n;this.v.gain.vlaue=q;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b)}c(){this.l.disconnect();this.v.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.v.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.v.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.v.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.v.gain,b,d,g)}}};self.me=class extends e{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.nb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.eb=this.o();this.eb.gain.value=d;this.l.connect(this.nb);this.l.connect(this.a);this.nb.connect(this.b);this.nb.connect(this.U);this.U.connect(this.eb);this.eb.connect(this.nb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.nb.disconnect();this.U.disconnect();this.eb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){const n=self.ea.od;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=n(b);this.m(this.eb.gain,n(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.le=class extends e{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Nd=this.Md="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.cb=this.f.createConvolver();this.cb.normalize=d;this.cb.buffer=b;this.l.connect(this.cb);this.l.connect(this.a);this.cb.connect(this.b)}c(){this.l.disconnect();this.cb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}ag(a,b){this.Md=a;this.Nd=b}Ua(){const a=
super.Ua();a.bufferOriginalUrl=this.Md;a.bufferUrl="";a.bufferType=this.Nd;return a}};self.pe=class extends e{constructor(a,b,d,g,n,q){super(a);this.R="flanger";this.g=[b,d,g,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.gb=this.o();this.gb.gain.value=n;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.u=this.f.createOscillator();this.u.frequency.value=g;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.gb);this.gb.connect(this.U);this.u.connect(this.I);this.I.connect(this.U.delayTime);this.u.start(0)}c(){this.u.stop(0);this.l.disconnect();this.U.disconnect();this.u.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.gb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.u.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.gb.gain,b/100,d,g)}}};self.re=class extends e{constructor(a,b,d,g,n,q,w){super(a);this.R="phaser";this.g=[b,d,g,n,q,w];this.l=this.o();this.a=this.o();this.a.gain.value=1-w/2;this.b=this.o();this.b.gain.value=w/2;this.v=this.f.createBiquadFilter();this.v.type="allpass";this.v.frequency.value=b;this.v.detune.value=
d;this.v.Q.value=g;this.u=this.f.createOscillator();this.u.frequency.value=q;this.I=this.o();this.I.gain.value=n;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b);this.u.connect(this.I);this.I.connect(this.v.frequency);this.u.start(0)}c(){this.u.stop(0);this.l.disconnect();this.v.disconnect();this.u.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.v.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.v.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.v.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.u.frequency,b,d,g)}}};self.qe=class extends e{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){const n=self.ea.od;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,g)}}};self.te=class extends e{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.u=this.f.createOscillator();this.u.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.u.connect(this.I);this.I.connect(this.h.gain);this.u.start(0)}c(){this.u.stop(0);this.u.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.I.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,d,g)}}};self.se=class extends e{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.tb=this.o();this.tb.gain.value=
0;this.u=this.f.createOscillator();this.u.frequency.value=b;this.u.connect(this.tb.gain);this.u.start(0);this.l.connect(this.tb);this.l.connect(this.a);this.tb.connect(this.b)}c(){this.u.stop(0);this.u.disconnect();this.tb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,d,g)}}};self.ne=class extends e{constructor(a,b,d,g,n,q){super(a);this.R="distortion";this.g=[b,d,g,n,q];this.l=this.o();this.ac=this.o();this.$b=this.o();this.bg(g,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.ec=this.f.createWaveShaper();this.Qc=new Float32Array(65536);this.jf(b,d);this.ec.curve=this.Qc;this.l.connect(this.ac);this.l.connect(this.a);this.ac.connect(this.ec);this.ec.connect(this.$b);
this.$b.connect(this.b)}c(){this.l.disconnect();this.ac.disconnect();this.ec.disconnect();this.$b.disconnect();this.b.disconnect();this.a.disconnect();super.c()}bg(a,b){.01>a&&(a=.01);this.ac.gain.value=a;this.$b.gain.value=Math.pow(1/a,.6)*b}jf(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.og(g,a,b);this.Qc[32768+d]=g;this.Qc[32768-d-1]=-g}}og(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.ea.Fg(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.ke=class extends e{constructor(a,b,d,g,n,q){super(a);this.R="compressor";this.g=[b,d,g,n,q];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=n;this.h.release.value=q}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.je=class extends e{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Qd=new Float32Array(this.h.frequencyBinCount);this.ce=new Uint8Array(b);this.ae=this.Na=0;this.i.Te(this)}c(){this.i.Vf(this);this.h.disconnect();super.c()}wa(){this.h.getFloatFrequencyData(this.Qd);this.h.getByteTimeDomainData(this.ce);const a=this.h.fftSize;let b=this.Na=0;for(var d=0;d<a;++d){let g=(this.ce[d]-128)/128;0>g&&(g=-g);
this.Na<g&&(this.Na=g);b+=g*g}d=self.ea.Je;this.Na=d(this.Na);this.ae=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}De(){return{tag:this.Y,index:this.Sd,peak:this.Na,rms:this.ae,binCount:this.h.frequencyBinCount,freqBins:this.Qd}}}};
